Repository syndesisio/fuse-online-install, pull requests merged in 2019-11, with the labels that each got.

#206 ENTESB-12130: Removes finalizers permission from syndesis-editor role
  release.sh
  templates/fuse-online-template.yml
Labels: approved, size/XS, status/review-requested

#207 BACKPORT changes for ENTESB-12133 & ENTESB-12130
  release.sh
  templates/README.md
  templates/fuse-online-template.yml
Labels: size/L, status/review-requested

#210 release 1.7.26
  fuse_online_config.sh
Labels: size/S

#205 [Install] Replace backticks with quotes
  install_ocp.sh
Labels: approved, size/XS

#204 [Install] Replace backticks with quotes
  install_ocp.sh
Labels: approved, size/XS

#212 ENTESB-12209: remove the -p / --project switch as causes failures in install_ocp.sh script
  common_config.sh
  install_ocp.sh
  libs/openshift_functions.sh
Labels: size/L, status/review-requested

#213 Secret linking and prepare for 1.8.13
  common_config.sh
  install_ocp.sh
  libs/openshift_functions.sh
  update_ocp.sh
Labels: size/M, status/review-requested
