Repository syndesisio/fuse-online-install, pull requests merged in 2019-08, with the labels that each got.

#167 fix #164: fix permission issue on volume
  install_ocp.sh
Labels: approved, backport master, size/XS

#173 fix #172: upgrade camel k image
  fuse_online_config.sh
Labels: approved, size/XS

#174 Typo fixed
  update_ocp.sh
Labels: size/XS, status/review-requested

#175 fix #165: fix repo for fuse-java-openshift
  install_ocp.sh
Labels: approved, backport master, size/XS

#176 fix #165: fix repo for fuse-java-openshift
  install_ocp.sh
Labels: approved, size/XS

#178 Dont include komodo and the postgres exporter as part of the upgrade …
  fuse_online_config.sh
Labels: size/XS

#180 remove not needed upgrade logic
  update_ocp.sh
Labels: approved, size/M, status/review-requested
