Repository syndesisio/fuse-online-install, pull requests merged in 2019-07, with the labels that each got.

#139 Fixes syndesisio/syndesis#5010: Use oauth proxy 4.1
  import_images.pl
  templates/fuse-online-image-streams.yml
Labels: status/review-requested

#141 Align operator role
  resources/fuse-online-operator.yml
  templates/fuse-online-operator.yml
Labels: approved

#147 Add back rolebinding and other references
  fuse_online_config.sh
  install_ocp.sh
  resources/fuse-online-image-streams.yml
  resources/fuse-online-operator.yml
  resources/fuse-online-template.yml
  templates/fuse-online-image-streams.yml
  update_ocp.sh
Labels: approved, size/XXL

#151 Fix data virt images and references
  README.md
  fuse_online_config.sh
  import_images.pl
  install_ocp.sh
  resources/fuse-online-image-streams.yml
  templates/fuse-online-image-streams.yml
Labels: approved, size/M

#154 Create resource for operator hub
  fuse_online_config.sh
  release.sh
  resources/fuse-online-template-oh.yml
  templates/fuse-online-image-streams.yml
Labels: size/S

#158 [#157] fixes kamel unknown option repository
  install_ocp.sh
Labels: approved, size/XS

#160 Fix ENTESB-11037: Change komodo tag back to `latest`
  resources/fuse-online-image-streams.yml
Labels: approved, size/XS

#152 fix #148, #149, #150: port from 1.7.x
  README.md
  import_images.pl
  install_ocp.sh
  templates/fuse-online-image-streams.yml
Labels: size/S

#156 [#155] Use tech preview namespace for camel-k
  install_ocp.sh
Labels: approved, size/XS, status/review-requested

#162 Fix #161: add extra permission to install user
  install_ocp.sh
Labels: approved, size/XS, status/review-requested

#163 Fixdvname
  import_images.pl
  resources/fuse-online-image-streams.yml
  resources/fuse-online-template-oh.yml
  templates/fuse-online-image-streams.yml
Labels: approved, size/S
