Repository syndesisio/fuse-online-install, pull requests merged in 2019-06, with the labels that each got.

#128 Adding knative permissions to fuse-online operator
  templates/fuse-online-operator.yml
Labels: approved

#125 Refer to latest oauth-proxy and prometheus image tags
  import_images.pl
Labels: approved

#132 Replace ClusterRole with Role
  install_ocp.sh
  install_test.sh
  resources/fuse-online-operator.yml
Labels: status/review-requested

#137 Operator online resources
  install_ocp.sh
  resources/fuse-online-operator.yml
  resources/fuse-online-template.yml
  templates/fuse-online-operator.yml
Labels: status/review-requested

#138 [ENTESB-10866] Changes to support new dv image
  fuse_online_config.sh
  fuse_online_config_template.sh
  import_images.pl
  release.sh
  resources/fuse-online-image-streams.yml
  resources/fuse-online-template.yml
  templates/fuse-online-image-streams.yml
  update_ocp.sh
Labels: approved, status/review-requested
