Repository syndesisio/fuse-online-install, pull requests merged in 2019-10, with the labels that each got.

#189 ENTESB-11837: extract binaries from productization and publish them
  .gitignore
  common_config.sh
  install_ocp.sh
  libs/docker_functions.sh
  release.sh
Labels: approved, size/L, status/review-requested

#190 chore: Cosmetic enhancements
  update_ocp.sh
Labels: approved, size/XS, status/review-requested

#192 partial fix(ENTESB-11369): allows oc versions from crc
  libs/openshift_functions.sh
  release.sh
Labels: approved, size/XS, status/review-requested

#193 chore(release): Fix config for next releases
  common_config.sh
  release.sh
Labels: approved, size/XS

#196 Preparations for the evaluation cluster provisioning
  templates/README.md
  templates/serviceaccount-as-oauthclient-restricted.yml
  utils/fuse_online_config.sh
  utils/import_images.pl
Labels: size/M

#199 [1.8.x] Fix Typo
  templates/README.md
Labels: size/XS

#197 Remove old way of installing syndesis CR
  install_ocp.sh
Labels: approved, size/M, status/review-requested

#200 ENTESB-12133: Adds missing datavirt configuration to template
  release.sh
  templates/fuse-online-template.yml
Labels: backport 1.8.x, size/L, status/review-requested

#201 Backport #200 manually
  release.sh
Labels: size/XS

#202 Fix typo in template generation
  release.sh
Labels: size/XS

#203 Correct instructions to mimic the eval cluster setup
  templates/README.md
Labels: size/XS
