Repository syndesisio/fuse-online-install, pull requests merged in 2019-04, with the labels that each got.

#79 Backport changes to 1.6.x
  README.md
  fuse_online_config.sh
  install_ocp.sh
  update_ocp.sh
Labels: approved

#87 Fix #85: add exporter image stream
  fuse_online_config.sh
  import_images.pl
  release.sh
  resources/fuse-online-image-streams.yml
  templates/fuse-online-image-streams.yml
Labels: approved, status/review-requested

#88 Fix #85: add exporter image stream
  fuse_online_config.sh
  import_images.pl
  release.sh
  resources/fuse-online-image-streams.yml
  templates/fuse-online-image-streams.yml
Labels: approved

#91 Fixes syndesis/#5141, adding copy of productized public proxy template that uses hardcoded v1.1.0 imagestream tag for oauth-proxy
  resources/syndesis-public-oauth-proxy.yml
Labels: approved

#97 Install secret for any 1.6.x release version
  update_ocp.sh
Labels: approved

#101 remove local declaration out of function context and fix condition to…
  update_ocp.sh
Labels: approved

#102 Recreate operator resources to include missing envs and roles
  update_ocp.sh
Labels: status/review-requested

#104 Recreate operator resources to include missing envs and roles
  fuse_online_config.sh
  update_ocp.sh
Labels: approved, status/review-requested

#105 Porting to 1.6.x: Recreate operator resources to include missing envs and roles
  update_ocp.sh
Labels: approved, status/review-requested

#99 [Update] Fix missing EOT
  update_ocp.sh
Labels: approved, status/review-requested

#100 [Update] Fix missing EOT
  update_ocp.sh
Labels: approved, status/review-requested

#106 Remove Camel-K resource when installing from template
  release.sh
Labels: approved, status/review-requested

#109 Adding maven repository property
  fuse_online_config_template.sh
Labels: approved

#112 Make sure sed -i works on mac and Linux
  release.sh
Labels: backport 1.6.x

#103 Related to #86: fix pull and error management
  install_ocp.sh
Labels: approved, status/review-requested

#114 ENTESB-10520: fix base image
  fuse_online_config.sh
  install_ocp.sh
Labels: approved, status/review-requested

#115 ENTESB-10520: fix base image
  fuse_online_config.sh
  install_ocp.sh
Labels: approved, status/review-requested
