Repository syndesisio/fuse-online-install, pull requests merged in 2020-02, with the labels that each got.

#217 Updates to master taken from 1.8.x branch
  common_config.sh
  install_ocp.sh
  update_ocp.sh
Labels: size/S

#218 Addresses logging failure and ENTESB-12633
  base_functions.sh
  default-cr.yml
  install_ocp.sh
  libs/openshift_functions.sh
Labels: size/L

#219 ENTESB-13037: Updates default-cr.yml with default values and comments
  default-cr.yml
Labels: pr/wip, size/M

#221 user doc (sort of): Edits to clarify routeHostname setting
  default-cr.yml
Labels: size/S

#220 Force pod recreate after link pull secret
  install_ocp.sh
  libs/openshift_functions.sh
Labels: size/M

#222 user doc (sort of): Removed lines about Jaeger
  default-cr.yml
Labels: size/S

#223 Minor fixes
  base_functions.sh
  utils/import_images.pl
Labels: size/XS

#224 Comment tweaks: added "Technology Preview" to those addons.
  default-cr.yml
Labels: size/S
