Repository syndesisio/fuse-online-install, pull requests merged in 2020-03, with the labels that each got.

#225 [fix] fixed indentation of default-cr.yml
  default-cr.yml
Labels: size/XS

#226 Fix default-cr.yaml identation
  default-cr.yml
Labels: size/XS

#227 [PublicApi] Comment out routeHostname value by default
  default-cr.yml
Labels: size/XS

#230 1.8 fix
  templates/fuse-online-template.yml
Labels: size/XS

#231 Fix 1.9 template (manually crafted and generation disabled)
  common_config.sh
  release.sh
  templates/README.md
  templates/fuse-online-template.yml
  utils/fuse_online_config.sh
  utils/import_images.pl
Labels: size/XL

#234 ENTESB-12854 Fuse online scripts break with space in path
  common_config.sh
  install_ocp.sh
  libs/docker_functions.sh
  libs/download_functions.sh
  libs/openshift_functions.sh
  release.sh
  update_ocp.sh
Labels: size/M

#228 [CR] Remove demoData
  default-cr.yml
Labels: size/XS

#232 Force pod recreation after link pull-secret
  install_ocp.sh
Labels: size/XS

#233 Force pod recreation after link pull-secret (1.9.x)
  install_ocp.sh
Labels: size/XS

#236 fix(ENTESB-13221): Update template to be more generic
  templates/fuse-online-template.yml
  utils/import_images.pl
Labels: size/XL
